name: Trigger auto deployment for bytepit-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ development ]
    paths:
    - '**'
    - '.github/workflows/bytepit-dev-AutoDeployTrigger-4176b2f4-b313-4bc0-a959-71c4775974fe.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BYTEPITDEV_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: bytepit.azurecr.io
          registryUsername: ${{ secrets.BYTEPITDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BYTEPITDEV_REGISTRY_PASSWORD }}
          containerAppName: bytepit-dev
          resourceGroup: BytePit
          imageToBuild: bytepit.azurecr.io/bytepit-dev:${{ github.sha }}
          

     

