name: Trigger auto deployment for bytepit-dev

on:
    pull_request:
        types: [closed]
        branches:
            - development
    # Allow manual trigger
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v2

            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.BYTEPITDEV_AZURE_CREDENTIALS }}

            - name: Build and push container image to registry
              uses: azure/container-apps-deploy-action@v2
              with:
                  appSourcePath: ${{ github.workspace }}
                  registryUrl: bytepit.azurecr.io
                  registryUsername: ${{ secrets.BYTEPITDEV_REGISTRY_USERNAME }}
                  registryPassword: ${{ secrets.BYTEPITDEV_REGISTRY_PASSWORD }}
                  containerAppName: bytepit-dev
                  resourceGroup: BytePit
                  imageToBuild: bytepit.azurecr.io/bytepit-dev:${{ github.sha }}
